### ISSUE TITLE
Code review: usage of NSString description

### ISSUE THREAD

**Issue by JanX2** [nicklockwood/RequestUtils#14]
I am currently reviewing this code and I don’t see what NSString’s -description method in many places. This is relying on it returning itself, which it doesn’t have to. 

Why not simply use -copy or the string itself?

**Comment by nicklockwood** [comment]
I'm using it in cases where the value may not be a string - e.g. it may be an NSNumber, or NSURL instead. Description always returns a string. Also, I've never encountered a situation where [string description] doesn't return the string - can you cite an example?

**Comment by JanX2** [comment]
No. But this is an implementation detail of the underlying system and I am a bit paranoid about relying on those objects currently returning strings without memory addresses or suchlike. 

But I can now understand why you do this.

**Comment by nicklockwood** [comment]
Yeah, in the cases where you removed it, it was redundant. I think that was probably just copypasta on my part.
